on:
  schedule:
    - cron: '0 23 * * *'

name: build-quarto-gt-examples-site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Print Quarto version
        run: |
          quarto --version

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            gt
            shiny
            tidyverse
            dplyr
            tidyr
            ggplot2
            lubridate
            paletteer
            janitor
            any::sessioninfo
          dependencies: '"hard"'

      - name: Install package
        run: R CMD INSTALL .

      - name: Generate Quarto files for website
        run: |
          Rscript -e 'gt:::write_gt_examples_qmd_files()'

      - name: Build Quarto site
        run: |
          quarto render gt_qmd_examples

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: 'gt_qmd_examples/_site'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          # these all default to 'true'
          enable-pull-request-comment: false
          enable-commit-comment: true
          enable-commit-status: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
